//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.16 at 12:58:07 AM PDT 
//


package com.inamik.template.jaxb.lib;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.inamik.template.jaxb.lib package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.inamik.template.jaxb.lib
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TemplateLib.Function }
     * 
     */
    public TemplateLib.Function createTemplateLibFunction() {
        return new TemplateLib.Function();
    }

    /**
     * Create an instance of {@link TemplateLib.Action.AnyAttribute }
     * 
     */
    public TemplateLib.Action.AnyAttribute createTemplateLibActionAnyAttribute() {
        return new TemplateLib.Action.AnyAttribute();
    }

    /**
     * Create an instance of {@link TemplateLib.Filter.Parameter }
     * 
     */
    public TemplateLib.Filter.Parameter createTemplateLibFilterParameter() {
        return new TemplateLib.Filter.Parameter();
    }

    /**
     * Create an instance of {@link TemplateLib.Filter.AnyParameter }
     * 
     */
    public TemplateLib.Filter.AnyParameter createTemplateLibFilterAnyParameter() {
        return new TemplateLib.Filter.AnyParameter();
    }

    /**
     * Create an instance of {@link TemplateLib.Function.Example }
     * 
     */
    public TemplateLib.Function.Example createTemplateLibFunctionExample() {
        return new TemplateLib.Function.Example();
    }

    /**
     * Create an instance of {@link TemplateLib.Action.Example }
     * 
     */
    public TemplateLib.Action.Example createTemplateLibActionExample() {
        return new TemplateLib.Action.Example();
    }

    /**
     * Create an instance of {@link TemplateLib }
     * 
     */
    public TemplateLib createTemplateLib() {
        return new TemplateLib();
    }

    /**
     * Create an instance of {@link TemplateLib.Action.Attribute }
     * 
     */
    public TemplateLib.Action.Attribute createTemplateLibActionAttribute() {
        return new TemplateLib.Action.Attribute();
    }

    /**
     * Create an instance of {@link TemplateLib.Filter }
     * 
     */
    public TemplateLib.Filter createTemplateLibFilter() {
        return new TemplateLib.Filter();
    }

    /**
     * Create an instance of {@link TemplateLib.Function.Parameter }
     * 
     */
    public TemplateLib.Function.Parameter createTemplateLibFunctionParameter() {
        return new TemplateLib.Function.Parameter();
    }

    /**
     * Create an instance of {@link TemplateLib.Function.AnyParameter }
     * 
     */
    public TemplateLib.Function.AnyParameter createTemplateLibFunctionAnyParameter() {
        return new TemplateLib.Function.AnyParameter();
    }

    /**
     * Create an instance of {@link TemplateLib.Filter.Example }
     * 
     */
    public TemplateLib.Filter.Example createTemplateLibFilterExample() {
        return new TemplateLib.Filter.Example();
    }

    /**
     * Create an instance of {@link TemplateLib.Action }
     * 
     */
    public TemplateLib.Action createTemplateLibAction() {
        return new TemplateLib.Action();
    }

}
