//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.16 at 12:58:07 AM PDT 
//


package com.inamik.template.jaxb.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.inamik.template.jaxb.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.inamik.template.jaxb.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TemplateConfig.Cache }
     * 
     */
    public TemplateConfig.Cache createTemplateConfigCache() {
        return new TemplateConfig.Cache();
    }

    /**
     * Create an instance of {@link TemplateConfig.UseLib }
     * 
     */
    public TemplateConfig.UseLib createTemplateConfigUseLib() {
        return new TemplateConfig.UseLib();
    }

    /**
     * Create an instance of {@link TemplateConfig }
     * 
     */
    public TemplateConfig createTemplateConfig() {
        return new TemplateConfig();
    }

}
